import Head from "next/head";
import TodoForm from "../components/TodoForm";
import TodoFilter from "@/components/TodoFilter";
import TodoList from "@/components/TodoList";
import React, { useState, useEffect } from "react";

export default function Home() {
  const [searchQuery, setSearchQuery] = useState<string>("");
  const [filteredTasks, setFilteredTasks] = useState<string[]>([]);
  const [tasks, setTasks] = useState<string[]>([
    "Первая задача",
    "Вторая задача",
    "Третья задача",
  ]);

  const addTask = (value: string) => {
    setTasks((prevTasks) => [...prevTasks, value.trim()]);
  };

  const removeTask = (index: number) => {
    setTasks((prevTasks) => {
      const newTasks = [...prevTasks];
      newTasks.splice(index, 1);
      return newTasks;
    });
  };

  const updateTask = (id: number, text: string) => {
    setTasks((prevTasks) => {
      const newTasks = [...prevTasks];
      newTasks[id] = text;
      return newTasks;
    });
  };

  useEffect(() => {
    if (searchQuery.trim() === "") {
      setFilteredTasks(tasks);
    } else {
      setFilteredTasks(tasks.filter((task) => task.includes(searchQuery)));
    }
  }, [tasks, searchQuery]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container pt-5">
          <div className="row">
            <section className="col-lg-3 col-md-5">
              <TodoForm addTask={addTask} />
            </section>
            <section className="col offset-1">
              <TodoFilter
                searchQuery={searchQuery}
                setSearchQuery={setSearchQuery}
              />
              <TodoList
                tasks={filteredTasks}
                removeTask={removeTask}
                updateTask={updateTask}
              />
            </section>
          </div>
        </div>
      </main>
    </>
  );
}
